#!/bin/bash

# Copyright (c) 2018-2020, The Investcoin Project, GRIF-IT

case $1 in
   config)
        cat <<'EOM'
graph_title Height
graph_vlabel height
graph_category investcoin
height.label height
height.type COUNTER
EOM
        exit 0;;
esac

printf "height.value "
/home/user/investcoin_bin/connectivity_tool --ip=127.0.0.1 --rpc_port=8081 --timeout=1000 --rpc_get_daemon_info | grep height | cut -d ' ' -f2
