#!/bin/bash

# Copyright (c) 2018-2020, The Investcoin Project, GRIF-IT

case $1 in
   config)
        cat <<'EOM'
graph_title outgoing_connections_count
graph_vlabel outgoing_connections_count
graph_category investcoin
outgoing_connections_count.label outgoing_connections_count
EOM
        exit 0;;
esac

printf "outgoing_connections_count.value "
/home/user/investcoin_bin/connectivity_tool --ip=127.0.0.1 --rpc_port=8081 --timeout=1000 --rpc_get_daemon_info | grep outgoing_connections_count | cut -d ' ' -f2
